<section>

   <div class="container">
    <form method="post" id="adminForm">
        <div class="card-title" style="padding: 40px;"><h3>Change your admin account email and password</h3></div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Actual Password</label>
            <input type="password" class="form-control" id="actual-password" name="actual-password" placeholder="Actual Password">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">New Password</label>
            <input type="password" class="form-control" id="new-password" name="new-password" placeholder="New Password">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Confirm Password</label>
            <input type="password" class="form-control" id="confirm-password" name="confirm-password" placeholder="Confirm Password">
        </div>
        <button type="submit" class="btn btn-primary" onclick="updateAdmin()" >Update Admin</button>
    </form>
   </div>


</section>

<script>

    function updateAdmin() {

        $.ajax({

            type : 'post',
            data : $('#adminForm').serialize(),
            url : '/admin/updateAdmin',
            success : function(r) {

                if(r != 'done'){

                    alert(r);
                }
                else {

                    alert('Your Admin account has been updated');
                    document.getElementById('adminForm').reset();

                }
            },
            error : function() {

                alert('Sorry, something has happen');
                document.getElementById('adminForm').reset();
            }

        })

    }

</script>