<section>


    <div class="container">
        <form method="post" id="employeeForm">
            <div class="card-title" style="padding: 40px;"><h3>Update Employee</h3></div>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" aria-describedby="emailHelp" placeholder="Enter name" value="<?php if(!empty($this->employee)) { echo $this->employee['emp_name']; } ?>">
            </div>
            <div class="form-group">
                <label for="position">Position</label>
                <input type="text" class="form-control" id="position" name="position" aria-describedby="emailHelp" placeholder="Enter position" value="<?php if(!empty($this->employee)) { echo $this->employee['emp_position']; } ?>">
            </div>
            <div class="form-group">
                <label for="office">Office</label>
                <input type="text" class="form-control" id="office" name="office" aria-describedby="emailHelp" placeholder="Enter office" value="<?php if(!empty($this->employee)) { echo $this->employee['emp_office']; } ?>">
            </div>
            <div class="form-group">
                <label for="age">Age</label>
                <input type="number" class="form-control" id="age" name="age" aria-describedby="emailHelp" placeholder="Enter age" value="<?php if(!empty($this->employee)) { echo $this->employee['emp_age']; } ?>">
            </div>
            <div class="form-group">
                <label for="salary">Salary</label>
                <input type="number" class="form-control" id="salary" name="salary" aria-describedby="emailHelp" placeholder="Enter salary" value="<?php if(!empty($this->employee)) { echo $this->employee['emp_salary']; } ?>">
            </div>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email" value="<?php if(!empty($this->employee)) { echo $this->employee['emp_email']; } ?>">
            </div>

            <button type="submit" class="btn btn-primary" onclick="updateEmployee(<?php if(!empty($this->employee)) { echo $this->employee['emp_id']; } ?>);" >Update Employee</button>
        </form>
    </div>


</section>

<script>

    function updateEmployee(employeeId) {

        $.ajax({

            type : 'post',
            data: $('#employeeForm').serialize(),
            url : '/admin/updateEmp/'+ employeeId,
            success : function (r) {

                if(r != 'done'){

                    alert(r);
                }
                else {

                    alert('Your employee has been updated');
                    document.location.href = '/admin/update-employees';

                }
            },
            error : function() {

                alert('Sorry, something has happen');
                document.getElementById('employeeForm').reset();
            }


        })

    }

</script>